function Analysis=AB_DataSort(Analysis,FilterName,thisFilter)
%AB_Data sorts the data generated by AB_DataProcess based on the filter
%specified in 'FilterName'.
%
%function designed by Quentin 2016 for Analysis_Photometry

%% Filter
FilterName=strrep(FilterName,' ','_');
thistype=FilterName;
% recovery of filter if not specified
if nargin==2 || isempty(thisFilter)==1
    if isfield(Analysis.Filters,thistype)
thisFilter=Analysis.Filters.(thistype);
    else
        disp(['Unable to sort data based on filter ' thistype]);
        return
    end
end
% Check whether data have already been filtered using the specified filter
if isfield(Analysis,thistype)
    disp(['Data for ' thistype ' have already been computed']);
    return
end
%% Extract Data
    Analysis.(thistype).Name                        =strrep(FilterName,'_',' ');
    Analysis.(thistype).nTrials                     =nnz(thisFilter);
    Analysis.(thistype).IgnoredTrials               =Analysis.AllData.nTrials-Analysis.(thistype).nTrials;
if Analysis.(thistype).nTrials>0
    Analysis=AB_DataSort_FieldMatch(Analysis,FilterName,thisFilter);
    Analysis=AB_DataSort_Rasters(Analysis,FilterName);
    Analysis=AB_DataSort_Average(Analysis,FilterName);
end  
%% Event detection
if Analysis.Parameters.EventDetection.Detection
    Analysis=AB_DataSort_Events(Analysis,thistype);
end
end