function [GTP,GTPB]=AP_GoNogo_GroupToPlot(Analysis)
%
%
%function designed by Quentin 2017
GTP={};
GTPB={};
index=0;
indexb=0;

index=index+1;
GTP{index,1}='CueAvsCueB_EasyTrials';
GTP{index,2}={'CueA_Go_Hit',                {'type_1','Go','LicksOutcome'};...
          'CueA_Go_Miss',                   {'type_1','Nogo'};...
          'CueB_Nogo_CorrectRej',           {'type_2','Nogo'};...
          'CueB_Nogo_FalseAlarm',           {'type_2','Go'}};
      
% if Analysis.Parameters.Wheel
%     indexb=indexb+1;      
% GTPB{indexb,1}='Go_Run';
% GTPB{indexb,2}={'Go_Hit_Run',           {'Go','Run'};...
%           'Go_Hit_NoRun',            	  {'Go','RunInv'}};
    
%     
%     indexb=indexb+1;      
% GTPB{indexb,1}='CueA_Run';
% GTPB{indexb,2}={'CueA_Go_Hit_Run',           {'type_1','Go','Run'};...
%           'CueA_Go_Hit_NoRun',            	{'type_1','Go','RunInv'};...
%           'CueA_Go_Miss_Run',               {'type_1','Nogo','Run'};...
%           'CueA_Go_Miss_NoRun',             {'type_1','Nogo','RunInv'}};
%     indexb=indexb+1;
% GTPB{indexb,1}='CueB_Run';
% GTPB{indexb,2}={'CueB_Nogo_FalseAlarm_Run',      	{'type_2','Go','Run'};...
%           'CueB_Nogo_FalseAlarm_NoRun',    	{'type_2','Go','RunInv'};...
%           'CueB_Nogo_CorrectRej_Run',       {'type_2','Nogo','Run'};...
%           'CueB_Nogo_CorrectRej_NoRun',     {'type_2','Nogo','RunInv'}};
% end
% 
% if Analysis.Parameters.Pupillometry
% 	indexb=indexb+1;
% GTPB{indexb,1}='CueA_Pupil';
% GTPB{indexb,2}={'CueA_Go_Hit_Pupil',          {'type_1','Go','Pupil','PupilNaN','LicksOutcome'};...
%           'CueA_Go_Hit_noPupil',            {'type_1','Go','PupilInv','PupilNaN'};...
%           'CueA_Go_Miss_Pupil',             {'type_1','Nogo','Pupil','PupilNaN'};...
%           'CueA_Go_Miss_NoPupil',           {'type_1','Nogo','PupilInv','PupilNaN'}};
% 	indexb=indexb+1;
% GTPB{indexb,1}='CueB_Pupil';
% GTPB{indexb,2}={'CueB_Nogo_FalseAlarm_Pupil',      	{'type_2','Go','Pupil','PupilNaN'};...
%           'CueB_Nogo_FalseAlarm_NoPupil',    	{'type_2','Go','PupilInv','PupilNaN'};...
%           'CueB_Nogo_CorrectRej_Pupil',       {'type_2','Nogo','Pupil','PupilNaN'};...
%           'CueB_Nogo_CorrectRej_NoPupil',     {'type_2','Nogo','PupilInv','PupilNaN'}};
% end
% 
if Analysis.Parameters.nbOfTrialTypes==4
	index=index+1;
GTP{index,1}='CueCvsCueD_HardTrials';
GTP{index,2}={'CueC_Go_Hit',                    {'type_3','Go','LicksOutcome'};...
              'CueC_Go_Miss',                   {'type_3','Nogo'};...
              'CueD_Nogo_CorrectRej',           {'type_4','Nogo'};...
              'CueD_Nogo_FalseAlarm',           {'type_4','Go'}}; 
% if Analysis.Parameters.Wheel
% 	indexb=indexb+1;
% GTPB{indexb,1}='CueC_Run';
% GTPB{indexb,2}={'CueC_Go_Hit_Run',                {'type_3','Go','Run'};...
%             'CueC_Go_Hit_NoRun',              {'type_3','Go','RunInv'};
%             'CueC_Go_Miss_Run',               {'type_3','Nogo','Run'};...
%             'CueC_Go_Miss_NoRun',             {'type_3','Nogo','RunInv'}};
%       indexb=indexb+1;
% GTPB{indexb,1}='CueD_Run';
% GTPB{indexb,2}={'CueD_Nogo_FalseAlarm_Run',      	{'type_4','Go','Run'};...
%           'CueD_Nogo_FalseAlarm_NoRun',    	{'type_4','Go','RunInv'};
%           'CueD_Nogo_CorrectRej_Run',       {'type_4','Nogo','Run'};...
%           'CueD_Nogo_CorrectRej_NoRun',     {'type_4','Nogo','RunInv'}};
% end
if Analysis.Parameters.Pupillometry
      indexb=indexb+1;
GTPB{indexb,1}='GoNoGo_Behavior';
GTPB{indexb,2}={'CueA_Go_Hit_PupNaN',                {'type_1','Go','PupilNaN','LicksOutcome'};...
                'CueB_Nogo_FA_PupNaN',              {'type_2','Go','PupilNaN'};...
                'CueC_Go_Hit_PupNaN',                {'type_3','Go','PupilNaN','LicksOutcome'};...
                'CueD_Nogo_FA_PupNaN',              {'type_4','Go','PupilNaN'}};
            
%       indexb=indexb+1;
% GTPB{indexb,1}='CueD_Pupil';
% GTPB{indexb,2}={'CueD_Nogo_FalseAlarm_Pupil',       {'type_4','Go','Pupil','PupilNaN'};...
%           'CueD_Nogo_FalseAlarm_NoPupil',     {'type_4','Go','PupilInv','PupilNaN'};
%           'CueD_Nogo_CorrectRej_Pupil',       {'type_4','Nogo','Pupil','PupilNaN'};...
%           'CueD_Nogo_CorrectRej_NoPupil',     {'type_4','Nogo','PupilInv','PupilNaN'}}; 
%       indexb=indexb+1;
% GTPB{indexb,1}='CueAvsCueB_CleanPupil';
% GTPB{indexb,2}={'CueA_Go_Hit_OKPupil',         {'type_1','Go','PupilNaN'};...
%           'CueA_Go_Miss_OKPupil',            {'type_1','Nogo','PupilNaN'};
%           'CueB_Nogo_FalseAlarm_OKPupil',    {'type_2','Go','PupilNaN'};...
%           'CueB_Nogo_CorrectRej_OKPupil',    {'type_2','Nogo','PupilNaN'}};
%       indexb=indexb+1;
% GTPB{indexb,1}='CueCvsCueD_CleanPupil';
% GTPB{indexb,2}={'CueC_Go_Hit_OKPupil',         {'type_3','Go','PupilNaN'};...
%           'CueC_Go_Miss_OKPupil',            {'type_3','Nogo','PupilNaN'};
%           'CueD_Nogo_FalseAlarm_OKPupil',    {'type_4','Go','PupilNaN'};...
%           'CueD_Nogo_CorrectRej_OKPupil',    {'type_4','Nogo','PupilNaN'}};    
end
end
end