function GROUPAnalysis =AP_Analyze_Group(Analysis,GROUPAnalysis,LastAnalysis)

if nargin <3
    LastAnalysis =0;
end

if nargin <2
end

trialNames =Analysis.Parameters.TrialNames;
trialTypes =trialNames(~contains(trialNames,'blank'));

%% define filters using pre-existing sub-filters

filterContainer                    =containers.Map;
filterContainer('Cue A Reward')    ={'Cue_A','Reward','LicksOutcome'};
filterContainer('Cue A Omission')  ={'Cue_A','Omission'};
filterContainer('Cue B Reward')    ={'Cue_B','Reward','LicksOutcome'};
filterContainer('Cue B Omission')  ={'Cue_B','Omission'};
filterContainer('Cue C Reward')    ={'Cue_C','Reward','LicksOutcome'};
filterContainer('Cue C Omission')  ={'Cue_C','Omission'};
filterContainer('Uncued Reward')   ={'Uncued','Reward','LicksOutcome'};
filterContainer('Uncued Omission') ={'Uncued','Omission'};

for tt              =1:length(trialTypes)
    trialType       =trialTypes{tt};
    filterNames     =filterContainer(trialType);
    filters         =zeros(length(filterNames),Analysis.Parameters.nTrials);
    for filt        =1:length(filterNames)
    subFilt         =Analysis.Filters.(filterNames{filt})';
    filters(filt,:) =subFilt;
    end
    intersection    =all(filters,1);                                        % intersection of sub-filters
    filterContainer(trialType)=intersection; 
end

if ~exist('GROUPAnalysis','var')
    CueA =any([filterContainer('Cue A Reward');                         ...
               filterContainer('Cue A Omission')]);
    GROUPAnalysis.CueA.Cue.firstPtime  =[median(                        ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueA),'omitnan')];
    GROUPAnalysis.CueA.Cue.firstJitter =[std(                           ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueA),'omitnan')];
    GROUPAnalysis.CueA.Cue.firstPprom  =[median(                        ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Cue(CueA),'omitnan')];
% %     GROUPAnalysis.CueA.Rew.firstPtime  =[median(                        ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueA),'omitnan')];
% %     GROUPAnalysis.CueA.Rew.firstJitter =[std(                           ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueA),'omitnan')];
% %     GROUPAnalysis.CueA.Rew.firstPprom  =[median(                        ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPprom.Rew(CueA),'omitnan')];  
    GROUPAnalysis.CueA.Spont.firstPtime  =[median(                      ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueA),'omitnan')];
    GROUPAnalysis.CueA.Spont.firstJitter =[std(                         ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueA),'omitnan')];
    GROUPAnalysis.CueA.Spont.firstPprom  =[median(                      ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Rew(CueA),'omitnan')];                           
    CueB =any([filterContainer('Cue B Reward');                         ...
               filterContainer('Cue B Omission')]);
    GROUPAnalysis.CueB.Cue.firstPtime  =[median(                        ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueB),'omitnan')];
    GROUPAnalysis.CueB.Cue.firstJitter =[std(                           ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueB),'omitnan')];
    GROUPAnalysis.CueB.Cue.firstPprom  =[median(                        ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Cue(CueB),'omitnan')];
% %     GROUPAnalysis.CueB.Rew.firstPtime  =[median(                        ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueB),'omitnan')];
% %     GROUPAnalysis.CueB.Rew.firstJitter =[std(                           ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueB),'omitnan')];
% %     GROUPAnalysis.CueB.Rew.firstPprom  =[median(                        ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPprom.Rew(CueB),'omitnan')];  
    GROUPAnalysis.CueB.Spont.firstPtime  =[median(                      ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueB),'omitnan')];
    GROUPAnalysis.CueB.Spont.firstJitter =[std(                         ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueB),'omitnan')];
    GROUPAnalysis.CueB.Spont.firstPprom  =[median(                      ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Rew(CueB),'omitnan')]; 
    CueC =any([filterContainer('Cue C Reward');                         ...
               filterContainer('Cue C Omission')]);
    GROUPAnalysis.CueC.Cue.firstPtime  =[median(                        ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueC),'omitnan')];
    GROUPAnalysis.CueC.Cue.firstJitter =[std(                           ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueC),'omitnan')];
    GROUPAnalysis.CueC.Cue.firstPprom  =[median(                        ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Cue(CueC),'omitnan')];
% %     GROUPAnalysis.CueC.Rew.firstPtime  =[median(                        ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueC),'omitnan')];
% %     GROUPAnalysis.CueC.Rew.firstJitter =[std(                           ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueC),'omitnan')];
% %     GROUPAnalysis.CueC.Rew.firstPprom  =[median(                        ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPprom.Rew(CueC),'omitnan')];  
    GROUPAnalysis.CueC.Spont.firstPtime  =[median(                      ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueC),'omitnan')];
    GROUPAnalysis.CueC.Spont.firstJitter =[std(                         ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueC),'omitnan')];
    GROUPAnalysis.CueC.Spont.firstPprom  =[median(                      ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Rew(CueC),'omitnan')]; 
else
    CueA =any([filterContainer('Cue A Reward');                         ...
               filterContainer('Cue A Omission')]);
    GROUPAnalysis.CueA.Cue.firstPtime  =[GROUPAnalysis.CueA.Cue.        ...
                                         firstPtime,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueA),'omitnan')];
    GROUPAnalysis.CueA.Cue.firstJitter =[GROUPAnalysis.CueA.Cue.        ...
                                         firstJitter,std(               ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueA),'omitnan')];
    GROUPAnalysis.CueA.Cue.firstPprom  =[GROUPAnalysis.CueA.Cue.        ...
                                         firstPprom,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Cue(CueA),'omitnan')];
% %     GROUPAnalysis.CueA.Rew.firstPtime  =[GROUPAnalysis.CueA.Rew.        ...
% %                                          firstPtime,median(             ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueA),'omitnan')];
% %     GROUPAnalysis.CueA.Rew.firstJitter =[GROUPAnalysis.CueA.Rew.        ...
% %                                          firstJitter,std(               ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueA),'omitnan')];
% %     GROUPAnalysis.CueA.Rew.firstPprom  =[GROUPAnalysis.CueA.Rew.        ...
% %                                          firstPprom,median(             ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPprom.Rew(CueA),'omitnan')];  
    GROUPAnalysis.CueA.Spont.firstPtime  =[GROUPAnalysis.CueA.Spont.    ...
                                         firstPtime,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueA),'omitnan')];
    GROUPAnalysis.CueA.Spont.firstJitter =[GROUPAnalysis.CueA.Spont.    ...
                                         firstJitter,std(               ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueA),'omitnan')];
    GROUPAnalysis.CueA.Spont.firstPprom  =[GROUPAnalysis.CueA.Spont.    ...
                                         firstPprom,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Rew(CueA),'omitnan')];                           
    CueB =any([filterContainer('Cue B Reward');                         ...
               filterContainer('Cue B Omission')]);
    GROUPAnalysis.CueB.Cue.firstPtime  =[GROUPAnalysis.CueB.Cue.        ...
                                         firstPtime,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueB),'omitnan')];
    GROUPAnalysis.CueB.Cue.firstJitter =[GROUPAnalysis.CueB.Cue.        ...
                                         firstJitter,std(               ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueB),'omitnan')];
    GROUPAnalysis.CueB.Cue.firstPprom  =[GROUPAnalysis.CueB.Cue.        ...
                                         firstPprom,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Cue(CueB),'omitnan')];
% %     GROUPAnalysis.CueB.Rew.firstPtime  =[GROUPAnalysis.CueB.Rew.        ...
% %                                          firstPtime,median(             ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueB),'omitnan')];
% %     GROUPAnalysis.CueB.Rew.firstJitter =[GROUPAnalysis.CueB.Rew.        ...
% %                                          firstJitter,std(               ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueB),'omitnan')];
% %     GROUPAnalysis.CueB.Rew.firstPprom  =[GROUPAnalysis.CueB.Rew.        ...
% %                                          firstPprom,median(             ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPprom.Rew(CueB),'omitnan')];  
    GROUPAnalysis.CueB.Spont.firstPtime  =[GROUPAnalysis.CueB.Spont.    ...
                                         firstPtime,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueB),'omitnan')];
    GROUPAnalysis.CueB.Spont.firstJitter =[GROUPAnalysis.CueB.Spont.    ...
                                         firstJitter,std(               ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueB),'omitnan')];
    GROUPAnalysis.CueB.Spont.firstPprom  =[GROUPAnalysis.CueB.Spont.    ...
                                         firstPprom,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Rew(CueB),'omitnan')]; 
    CueC =any([filterContainer('Cue C Reward');                         ...
               filterContainer('Cue C Omission')]);
    GROUPAnalysis.CueC.Cue.firstPtime  =[GROUPAnalysis.CueC.Cue.        ...
                                         firstPtime,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueC),'omitnan')];
    GROUPAnalysis.CueC.Cue.firstJitter =[GROUPAnalysis.CueC.Cue.        ...
                                         firstJitter,std(               ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Cue(CueC),'omitnan')];
    GROUPAnalysis.CueC.Cue.firstPprom  =[GROUPAnalysis.CueC.Cue.        ...
                                         firstPprom,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Cue(CueC),'omitnan')];
% %     GROUPAnalysis.CueC.Rew.firstPtime  =[GROUPAnalysis.CueC.Rew.        ...
% %                                          firstPtime,median(             ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueC),'omitnan')];
% %     GROUPAnalysis.CueC.Rew.firstJitter =[GROUPAnalysis.CueC.Rew.        ...
% %                                          firstJitter,std(               ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPtime.Rew(CueC),'omitnan')];
% %     GROUPAnalysis.CueC.Rew.firstPprom  =[GROUPAnalysis.CueC.Rew.        ...
% %                                          firstPprom,median(             ...
% %                                          Analysis.AllData.Photo_470.    ...
% %                                          firstPprom.Rew(CueC),'omitnan')];  
    GROUPAnalysis.CueC.Spont.firstPtime  =[GROUPAnalysis.CueC.Spont.    ...
                                         firstPtime,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueC),'omitnan')];
    GROUPAnalysis.CueC.Spont.firstJitter =[GROUPAnalysis.CueC.Spont.    ...
                                         firstJitter,std(               ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPtime.Rew(CueC),'omitnan')];
    GROUPAnalysis.CueC.Spont.firstPprom  =[GROUPAnalysis.CueC.Spont.    ...
                                         firstPprom,median(             ...
                                         Analysis.AllData.Photo_470.    ...
                                         firstPprom.Rew(CueC),'omitnan')]; 
end

if LastAnalysis
    GROUPAnalysis.CueA.Cue.firstPtime  =[mean(GROUPAnalysis.CueA.Cue.   ...
                                         firstPtime)];
    GROUPAnalysis.CueA.Cue.firstJitter =[mean(GROUPAnalysis.CueA.Cue.   ...
                                         firstJitter)];
    GROUPAnalysis.CueA.Cue.firstPprom  =[mean(GROUPAnalysis.CueA.Cue.   ...
                                         firstPprom)];
    GROUPAnalysis.CueA.Rew.firstPtime  =[mean(GROUPAnalysis.CueA.Rew.   ...
                                         firstPtime)];
    GROUPAnalysis.CueA.Rew.firstJitter =[mean(GROUPAnalysis.CueA.Rew.   ...
                                         firstJitter)];
    GROUPAnalysis.CueA.Rew.firstPprom  =[mean(GROUPAnalysis.CueA.Rew.   ...
                                         firstPprom)];  
    GROUPAnalysis.CueA.Spont.firstPtime  =[mean(GROUPAnalysis.CueA.Spont. ...
                                         firstPtime)];
    GROUPAnalysis.CueA.Spont.firstJitter =[mean(GROUPAnalysis.CueA.Spont. ...
                                         firstJitter)];
    GROUPAnalysis.CueA.Spont.firstPprom  =[mean(GROUPAnalysis.CueA.Spont. ...
                                         firstPprom)];                           
    GROUPAnalysis.CueB.Cue.firstPtime  =[mean(GROUPAnalysis.CueB.Cue.   ...
                                         firstPtime)];
    GROUPAnalysis.CueB.Cue.firstJitter =[mean(GROUPAnalysis.CueB.Cue.   ...
                                         firstJitter)];
    GROUPAnalysis.CueB.Cue.firstPprom  =[mean(GROUPAnalysis.CueB.Cue.   ...
                                         firstPprom)];
    GROUPAnalysis.CueB.Rew.firstPtime  =[mean(GROUPAnalysis.CueB.Rew.   ...
                                         firstPtime)];
    GROUPAnalysis.CueB.Rew.firstJitter =[mean(GROUPAnalysis.CueB.Rew.   ...
                                         firstJitter)];
    GROUPAnalysis.CueB.Rew.firstPprom  =[mean(GROUPAnalysis.CueB.Rew.   ...
                                         firstPprom)];  
    GROUPAnalysis.CueB.Spont.firstPtime  =[mean(GROUPAnalysis.CueB.Spont. ...
                                         firstPtime)];
    GROUPAnalysis.CueB.Spont.firstJitter =[mean(GROUPAnalysis.CueB.Spont. ...
                                         firstJitter)];
    GROUPAnalysis.CueB.Spont.firstPprom  =[mean(GROUPAnalysis.CueB.Spont. ...
                                         firstPprom)];
    GROUPAnalysis.CueC.Cue.firstPtime  =[mean(GROUPAnalysis.CueC.Cue.   ...
                                         firstPtime)];
    GROUPAnalysis.CueC.Cue.firstJitter =[mean(GROUPAnalysis.CueC.Cue.   ...
                                         firstJitter)];
    GROUPAnalysis.CueC.Cue.firstPprom  =[mean(GROUPAnalysis.CueC.Cue.   ...
                                         firstPprom)];
    GROUPAnalysis.CueC.Rew.firstPtime  =[mean(GROUPAnalysis.CueC.Rew.   ...
                                         firstPtime)];
    GROUPAnalysis.CueC.Rew.firstJitter =[mean(GROUPAnalysis.CueC.Rew.   ...
                                         firstJitter)];
    GROUPAnalysis.CueC.Rew.firstPprom  =[mean(GROUPAnalysis.CueC.Rew.   ...
                                         firstPprom)];  
    GROUPAnalysis.CueC.Spont.firstPtime  =[mean(GROUPAnalysis.CueC.Spont. ...
                                         firstPtime)];
    GROUPAnalysis.CueC.Spont.firstJitter =[mean(GROUPAnalysis.CueC.Spont. ...
                                         firstJitter)];
    GROUPAnalysis.CueC.Spont.firstPprom  =[mean(GROUPAnalysis.CueC.Spont. ...
                                         firstPprom)];
end